### ISSUE TITLE
dashboard link used in recommendations_export view file at line 279 is not available. 

### ISSUE THREAD

**Issue by pxn83q5** [llooker/gcp_billing_block#1]
HI, 

The dashboard link "dashboards-next/63" used in recommendations_export view file at line 279 is not available. i unable to find the given dashboard label in dashboards folder. can some one help me with this ? 

dimension: project_name {
    sql: (select array_to_string(array_agg(REGEXP_EXTRACT(tr, r'.*googleapis.com/projects/(.*)/(?:regions|zones)/.*')),", ") from unnest(target_resources) as tr);;
    link: {
      label: "View Project Recommendations in Console"
      url: "{% unless project_name._value contains ',' %}https://console.cloud.google.com/home/recommendations?project={{ cloud_entity_id._value }}{% endunless %}"
    }
    link: {
      label: "Project Cost Dashboard"
      url: "{% unless project_name._value contains ',' %}/dashboards-next/63?Project%20ID={{ cloud_entity_id._value }}{% endunless %}"
    }
  }

**Comment by leighajarett** [comment]
Thanks for flagging this! I have fixed the issue with this commit https://github.com/llooker/gcp_billing_block/commit/924356f61bf322dbc73ba5fb6799a2c490159271
